"""Project-owned (external) adapter loading — the two-repo layout.

The adapter lives in the *project's* repo (``<repo>/.orchestration/``), generated by the
scaffold and loaded by path. Because it is not updated atomically with the engine, the
loader enforces CONTRACT_VERSION and duck-checks the full ProjectConfig surface at load,
so drift fails loudly up front instead of mid-run.
"""

from __future__ import annotations

import json

import pytest

from adapters.project.base import ADAPTER_CONTRACT_VERSION, ProjectConfig
from orchestrator import scaffold
from orchestrator.cli import main as cli
from orchestrator.project_loader import load_project, validate_config
from orchestrator.scaffold import load_kit_manifest, profile_from_languages, scaffold_adapter
from orchestrator.schemas.work import WorkItem
from tests.conftest import make_result


def _scaffold_external(tmp_path, name: str = "my-project"):
    """A project repo with its adapter at <repo>/.orchestration/ (the two-folder layout)."""
    proj = tmp_path / name
    proj.mkdir()
    prof = profile_from_languages(name, ["python"], load_kit_manifest())
    pkg = scaffold_adapter(name, profile=prof, into=proj, package_dir=proj / ".orchestration")
    return proj, pkg


def test_loads_project_owned_adapter_by_path(tmp_path) -> None:
    _, pkg = _scaffold_external(tmp_path)
    cfg = load_project(str(pkg))
    assert cfg.name == "my-project"
    assert isinstance(cfg, ProjectConfig)
    assert validate_config(cfg) == []
    # The profile records the contract the files were generated against.
    assert f"contract_version = {ADAPTER_CONTRACT_VERSION}" in (pkg / "profile.toml").read_text()


def test_contract_mismatch_fails_loudly(tmp_path) -> None:
    _, pkg = _scaffold_external(tmp_path)
    init = pkg / "__init__.py"
    init.write_text(init.read_text().replace(
        f"CONTRACT_VERSION = {ADAPTER_CONTRACT_VERSION}", "CONTRACT_VERSION = 999"))
    with pytest.raises(SystemExit, match="contract"):
        load_project(str(pkg))


def test_missing_contract_declaration_fails_loudly(tmp_path) -> None:
    _, pkg = _scaffold_external(tmp_path)
    init = pkg / "__init__.py"
    init.write_text(init.read_text().replace(
        f"CONTRACT_VERSION = {ADAPTER_CONTRACT_VERSION}", "_UNDECLARED = 0"))
    with pytest.raises(SystemExit, match="CONTRACT_VERSION"):
        load_project(str(pkg))


def test_incomplete_external_adapter_names_missing_members(tmp_path) -> None:
    pkg = tmp_path / ".orchestration"
    pkg.mkdir()
    (pkg / "__init__.py").write_text(
        f"CONTRACT_VERSION = {ADAPTER_CONTRACT_VERSION}\n"
        "class Nearly:\n"
        "    name = 'nearly'\n"
        "def get_config():\n"
        "    return Nearly()\n"
    )
    with pytest.raises(SystemExit, match="install_cmd"):
        load_project(str(pkg))


def test_stale_lint_cmd_mapping_warns_without_blocking(tmp_path, capsys) -> None:
    """#412: an adapter scaffolded before the leg remap keeps a `lint_cmd` no merge gate
    calls and no `types_cmd` at all, so its linter is unverified at merge — and it does not
    self-heal on an engine upgrade. Say so at load. Advisory: the adapter still loads."""
    _, pkg = _scaffold_external(tmp_path, "stale-project")
    cfg_py = pkg / "config.py"
    cfg_py.write_text(
        cfg_py.read_text()
        .replace("def types_cmd(self)", "def lint_cmd(self)")
        .replace("self.types_cmd()", "self.lint_cmd()")
    )

    cfg = load_project(str(pkg))

    assert cfg.name == "stale-project"  # advisory only
    err = capsys.readouterr().err
    assert "lint_cmd" in err and "types_cmd" in err and "orchestrator-scaffold" in err


def test_regenerated_adapter_does_not_warn(tmp_path, capsys) -> None:
    """The control for the warning above: a current adapter is silent, so the warning is a
    signal rather than noise every load prints."""
    _, pkg = _scaffold_external(tmp_path, "fresh-project")
    load_project(str(pkg))
    assert "lint_cmd" not in capsys.readouterr().err


def test_nonexistent_adapter_dir_fails_loudly(tmp_path) -> None:
    with pytest.raises(SystemExit, match="not found"):
        load_project(str(tmp_path / "nope" / ".orchestration"))


def test_module_path_loading_unchanged() -> None:
    cfg = load_project("tests.fakeproject")
    assert cfg.name == "fake"
    assert validate_config(cfg) == []


def test_cli_validate_external_adapter(tmp_path, capsys) -> None:
    _, pkg = _scaffold_external(tmp_path)
    assert cli(["--project", str(pkg), "validate"]) == 0
    out = json.loads(capsys.readouterr().out)
    assert out == {"project": "my-project", "valid": True, "missing": [],
                   "contract_version": ADAPTER_CONTRACT_VERSION}


def test_cli_run_commands_still_require_root_and_run() -> None:
    with pytest.raises(SystemExit):
        cli(["--project", "tests.fakeproject", "status"])


def test_scaffold_cli_defaults_dest_into_the_project(tmp_path, capsys) -> None:
    proj = tmp_path / "svc"
    proj.mkdir()
    assert scaffold.main(["--name", "svc", "--languages", "python", "--into", str(proj)]) == 0
    pkg = proj / ".orchestration"
    assert (pkg / "config.py").exists()
    assert (pkg / "profile.toml").exists()
    assert (proj / ".claude" / "agents").exists()  # kit still seeded alongside


def test_cli_drives_a_task_end_to_end_on_a_project_owned_adapter(
    tmp_path, capsys, monkeypatch
) -> None:
    proj, pkg = _scaffold_external(tmp_path)
    tasks = proj / "tasks.json"
    tasks.write_text(json.dumps({"T1": {"title": "wire the thing", "body": "do it"}}))
    monkeypatch.setenv("MY_PROJECT_TASKS", str(tasks))

    # The deterministic intake runner creates a real worktree off HEAD of the CWD repo —
    # make the project dir an isolated git repo and run there, so nothing touches this repo.
    import subprocess

    # Generated adapters run lint/typecheck at REVIEW. Keep those deterministic legs green
    # here: this smoke test exercises CLI plumbing, not the fixture repo's toolchain.
    config_type = type(load_project(str(pkg)))
    monkeypatch.setattr(
        config_type, "_run_gate",
        staticmethod(lambda argv, cwd: subprocess.CompletedProcess(argv, 0, "", "")),
    )
    # Same reason for the #391 worktree hooks: this fixture is a git repo with an adapter
    # in it, not an installed python project, so REVIEW's fresh reinstall has no
    # pyproject.toml to sync and no interpreter here resolves inside the worktree — intake
    # and review would (correctly) refuse. They are REMOVED rather than emptied because
    # mere presence is what routes REVIEW to an origin-verifying lane, and this test wants
    # the plain supervisor path. That the generated adapter DOES declare both is covered in
    # tests/test_bootstrap_scaffold.py.
    assert config_type.fresh_install_paths(config_type)  # not silently absent
    assert config_type.worktree_origin_probes(config_type)
    monkeypatch.delattr(config_type, "fresh_install_paths")
    monkeypatch.delattr(config_type, "worktree_origin_probes")

    for argv in (["git", "init", "-q"], ["git", "add", "-A"],
                 ["git", "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "init"]):
        subprocess.run(argv, cwd=proj, check=True)
    monkeypatch.chdir(proj)

    base = ["--root", str(tmp_path / "run-root"), "--run", "r1", "--project", str(pkg)]

    def run(*argv):
        assert cli([*base, *argv]) == 0
        out = capsys.readouterr().out.strip()
        return json.loads(out) if out and out != "null" else None

    run("init-run", "--lane", "full")
    run("add-task", "--task", "T1")
    recorded = []
    for _ in range(10):  # safety bound
        work = run("next", "--task", "T1")
        if work is None:
            break
        wi = WorkItem.model_validate(work)
        result_file = tmp_path / "result.json"
        result_file.write_text(make_result(wi).model_dump_json())
        recorded.append(run("record", "--result", str(result_file))["stage"])
    # intake is drained deterministically by `next`, so the supervisor records 5 model stages.
    assert recorded == ["scope", "implement", "test", "deliver", "review"]

    status = run("status")
    assert status["tasks"]["T1"]["state"] == "completed"
    assert (tasks.parent / "completed.log").read_text().startswith("T1")
