"""Frozen engine contracts (target.md §4 + §7)."""

from __future__ import annotations

from .enums import (
    LANE_DETERMINISTIC_STAGES,
    LANE_STAGES,
    MIGRATABLE_STATUS_VERSIONS,
    SCHEMA_VERSION,
    STAGE_ORDER,
    SUPPORTED_STATUS_VERSIONS,
    SUPPORTED_WORK_VERSIONS,
    TERMINAL_TASK_STATES,
    ExecutionLane,
    ExecutionMode,
    FailureKind,
    ImplementationBudget,
    Provider,
    QualityTier,
    ResultStatus,
    RunState,
    Stage,
    StageStatus,
    TaskState,
)
from .status import (
    Progress,
    ResumeCursor,
    ReviewFixup,
    Run,
    StageRecord,
    Task,
    TaskRef,
)
from .work import (
    LanePolicy,
    LaneUsed,
    StageResult,
    TokenUsage,
    WorkItem,
    compute_content_hash,
)

__all__ = [
    "SCHEMA_VERSION",
    # The #275 compatibility policy: which versions each plane accepts.
    "MIGRATABLE_STATUS_VERSIONS",
    "SUPPORTED_STATUS_VERSIONS",
    "SUPPORTED_WORK_VERSIONS",
    "STAGE_ORDER",
    "LANE_STAGES",
    "LANE_DETERMINISTIC_STAGES",
    "TERMINAL_TASK_STATES",
    "Stage",
    "ExecutionMode",
    "ExecutionLane",
    "QualityTier",
    "ImplementationBudget",
    "Provider",
    "ResultStatus",
    "RunState",
    "StageStatus",
    "TaskState",
    "FailureKind",
    "WorkItem",
    "StageResult",
    "LanePolicy",
    "LaneUsed",
    "TokenUsage",
    "compute_content_hash",
    "Run",
    "Task",
    "TaskRef",
    "StageRecord",
    "ReviewFixup",
    "ResumeCursor",
    "Progress",
]
