"""Back-compat re-export shim — the project-config contract moved inward (#273).

The canonical home is ``orchestrator.ports.project``: the engine OWNS these Protocols
and an adapter implements them, so the dependency arrow points inward (``adapters/`` →
``orchestrator/``, never the reverse).

This module stays because an external adapter generated by an older
``orchestrator-scaffold`` imports ``adapters.project.base`` from inside the project's own
repo, and those files are not updated atomically with the engine. It re-exports the same
objects — same classes, same ``ADAPTER_CONTRACT_VERSION`` — so ``isinstance`` checks and
the loader's contract comparison behave identically whichever path an adapter imports.

The contract SURFACE is unchanged by the move, so ``ADAPTER_CONTRACT_VERSION`` is
deliberately NOT bumped: a pre-#273 adapter is still a valid adapter.

New code should import from ``orchestrator.ports.project``.
"""

from __future__ import annotations

from orchestrator.ports.project import (
    ADAPTER_CONTRACT_VERSION,
    ProjectConfig,
    TaskSource,
    TaskSpec,
)

__all__ = [
    "ADAPTER_CONTRACT_VERSION",
    "ProjectConfig",
    "TaskSource",
    "TaskSpec",
]
